#
# Install/run elastalert
#

- name: check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  register: pip_is_installed
  changed_when: false

- block:

    - name: download get-pip.py
      get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp
    
    - name: install pip
      command: "python /tmp/get-pip.py"
    
    - name: delete get-pip.py
      file: state=absent path=/tmp/get-pip.py

  when: pip_is_installed.rc != 0
  
- name: yum update
  command: yum update -y

- name: Install Elastalert deps
  yum:
    name: 
      - gcc
      - gcc-c++
      - python-devel
      - libffi-devel
      - openssl-devel
    state: present

- name: Install Elastalert and dependencies
  pip:
    name:
      - six>=1.10.0
      - requests-toolbelt
      - requests-oauthlib>=0.6.1
      - ordereddict
      - defusedxml
      - argparse
      - s3transfer<0.2.0
      - python-dateutil<2.7.0
      - enum34
      - asn1crypto>=0.21.0
      - urllib3==1.21.1
      - elastalert

- name: Install Supervisor
  easy_install:
    name: supervisor
  become: true

- name: Create Elastalert directory
  file: path=/opt/elastalert/
    state=directory
    mode=0755
  become: true

- name: Create Elastalert rules directory
  file: path=/opt/elastalert/rules/
    state=directory
    mode=0755
  become: true

- name: Copy Elastalert config to directory
  template:
    src=config.yml.j2
    dest=/opt/elastalert/config.yml
  become: true

- name: Create Elastalert index
  shell: elastalert-create-index --config /opt/elastalert/config.yml 
  become: true

- name: Copy in Supervisord config
  template:
    src=supervisord.conf
    dest=/opt/elastalert/supervisord.conf
  become: true

- name: Launch Elastalert daemon
  shell: supervisord -c /opt/elastalert/supervisord.conf
  become: true
