#
# Install/run elastalert
#

- name: Install ius-release
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Update all packages
  command: yum update

- name: Install Python 3.6
  yum:
    name:
      - python36u 
      - python36u-libs 
      - python36u-devel 
      - python36u-pip
    state: present

- name: Install Elastalert deps
  yum:
    name: 
      - gcc
      - gcc-c++
      - python-devel
      - libffi-devel
      - openssl-devel

- name: Install Elastalert
  pip:
    name: elastalert
    executable: pip3.6
  become: true    

- name: Install Supervisord
  easy_install:
    name: supervisor
  become: true

- name: Create Elastalert directory
  file: path=/opt/elastalert/
    state=directory
    mode=0755
  become: true

- name: Create Elastalert rules directory
  file: path=/opt/elastalert/rules/
    state=directory
    mode=0755
  become: true

- name: Copy Elastalert config to directory
  template:
    src=config.yml.j2
    dest=/opt/elastalert/config.yml
  become: true

- name: Create Elastalert index
  shell: elastalert-create-index --config /opt/elastalert/config.yml 
  become: true

- name: Copy in Supervisord config
  template:
    src=supervisord.conf
    dest=/opt/elastalert/supervisord.conf
  become: true

- name: Launch Elastalert daemon
  shell: supervisord -c /opt/elastalert/supervisord.conf
  become: true
