name: Curl/Wget User Agent 
type: frequency
index: filebeat*
num_events: 1
timeframe:
  minutes: 15
filter:
- query:
    query_string: 
      query: "(message:curl OR message:wget) AND (message:GET OR message:POST)"
alert:
- "telegram"
telegram_bot_token: 471165926:AAHGbQmR4XiMI4Mu15xOLY28dgQNZ8M_z4c
telegram_room_id: "-255551161"

