name: Credential Harvest Hit
type: frequency
index: filebeat*
num_events: 1
timeframe:
  minutes: 15
filter:
- query:
    query_string: 
      query: 'message:"insert into victims"'
alert:
- "ms_teams"
ms_teams_webhook_url:
- "<webhook url here>"
ms_teams_alert_summary: "Credentials entered on phishing site"

