name: Potential C2 Sandbox
type: frequency
index: filebeat*
num_events: 1
timeframe:
  minutes: 15
filter:
- query:
    query_string: 
      query: 'message:"initial beacon" AND (message:"from Bob" OR message:"from Alice" or message:"from Apiary")'
alert:
- "ms_teams"
ms_teams_webhook_url:
- "<webhook url here>"
ms_teams_alert_summary: "New beacon potentially in a sandbox"

