name: URI Hit
type: frequency
index: filebeat*
num_events: 1
timeframe:
  minutes: 15
filter:
- query:
    query_string: 
      query: 'message:"/path/to/alert/on.html" AND (message:"GET" OR "POST")'
alert:
- "ms_teams"
ms_teams_webhook_url:
- "<webhook url here>"
ms_teams_alert_summary: "Traffic hit for specific path"

