---
#
# Playbook to install the ELK stack
#

- hosts: elk
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - group_vars/all.yml
  become: yes
  roles:
    - { role: elasticsearch }
    - { role: logstash, when: ((logging_backend is none) or (logging_backend == 'logstash')) }
    - { role: nginx }
    - { role: kibana }
    - { role: xpack, when: ((install_elasticsearch_xpack) or (install_kibana_xpack) or (install_logstash_xpack)) }
    - { role: instructions }
    - { role: elastalert }
